# Generated by Django 4.0.3 on 2022-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_restaurant_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
