# Generated by Django 4.0.3 on 2022-03-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_meal_isavailaible_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='position',
        ),
    ]
