# Generated by Django 4.0.3 on 2022-04-01 15:20

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_restaurant_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=0, max_length=63),
            preserve_default=False,
        ),
    ]
