# Generated by Django 4.0.3 on 2022-03-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_resto',
            field=models.BooleanField(default=False),
        ),
    ]
